# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ca42a969f4323071a59d77d6e68be6803aac1ea9e3f28fd3d9332030c03816132862c72cfe256023dc843a41a0f516fa72ed23fafa996e203cbb5d495180987

test:
  secret_key_base: 53afd05ab0b674cc4d8519a40526048aeb7a4f0898f80af67fa6106e1c6923e40e2a0229856606494d3df8158fe30fffc7e3ae8940e650eea97e555d57558f52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
